### ISSUE TITLE
TypeError: 'numpy.float64' object cannot be interpreted as an integer + tuple has no attribute shape

### ISSUE THREAD

**Issue by CDog94** [lihan97/KPGT#1]

**Comment by lihan97** [comment]
Hi,

I have tested our codes, but I did not get that error.  Did you modify the codes? In the original codes, the elements in the paths should be integers.

**Comment by c-dog75** [comment]
Hi Han Li,

Thanks for responding.

I have changed nothing in the codebase beyond run the commands you suggested. Unfortunately, the command 'conda env create' does not work - it provides a ton of conflict errors meaning I had to install more recent versions of the Python libraries.

Maybe this is causing the float issues, the current versions I am using are:

absl-py                       1.2.0
alabaster                     0.7.12
autopep8                      1.7.0
Babel                         2.10.3
brotlipy                      0.7.0
cachetools                    4.2.4
certifi                       2022.6.15
cffi                          1.15.1
charset-normalizer            2.1.0
click                         8.1.3
cloudpickle                   2.1.0
cryptography                  37.0.4
dgl-cu113                     0.9.0
dglgo                         0.0.2
dgllife                       0.3.0
docutils                      0.19
future                        0.18.2
google-auth                   1.35.0
google-auth-oauthlib          0.4.6
grpcio                        1.47.0
hyperopt                      0.2.7
idna                          3.3
imagesize                     1.4.1
isort                         5.10.1
Jinja2                        3.1.2
joblib                        1.1.0
lazy_loader                   0.1rc2
littleutils                   0.2.2
Markdown                      3.4.1
MarkupSafe                    2.1.1
networkx                      2.8.5
numpy                         1.23.1
numpydoc                      1.4.0
oauthlib                      3.2.0
ogb                           1.3.3
outdated                      0.2.1
packaging                     21.3
pandas                        1.4.3
pandas-flavor                 0.3.0
Pillow                        9.2.0
pip                           22.2.2
protobuf                      3.20.1
psutil                        5.9.1
py4j                          0.10.9.6
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycodestyle                   2.9.1
pycparser                     2.21
pydantic                      1.9.2
Pygments                      2.12.0
pyOpenSSL                     22.0.0
pyparsing                     3.0.9
PySocks                       1.7.1
python-dateutil               2.8.2
pytz                          2022.2
PyYAML                        6.0
rdkit-pypi                    2022.3.5
requests                      2.28.1
requests-oauthlib             1.3.1
rsa                           4.9
ruamel.yaml                   0.17.21
ruamel.yaml.clib              0.2.6
scikit-learn                  0.24.2
scipy                         1.9.0
setuptools                    64.0.0
six                           1.16.0
snowballstemmer               2.2.0
Sphinx                        5.1.1
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
tensorboard                   2.6.0
tensorboard-data-server       0.6.1
tensorboard-plugin-wit        1.8.1
threadpoolctl                 3.1.0
toml                          0.10.2
torch                         1.12.1
torchaudio                    0.12.1
torchvision                   0.13.1
tqdm                          4.64.0
typer                         0.6.1
typing_extensions             4.3.0
urllib3                       1.26.11
Werkzeug                      2.2.2
wheel                         0.37.1
xarray                        2022.6.0

Additioanlly, I am running Linux, specifically AWS' preconfigured Linux environment here.

https://www.amazonaws.cn/en/amis/

**Comment by lihan97** [comment]
Yes, I agree with you that this error may be due to the wrong versions of  python libraries. And I have tested 'conda env create' and it works properly. Could you deploy the environment and test the codes in another machine? Also, you can print the elements in the paths. The elements in the variable 'paths' should be integers if the code run properly.
