### ISSUE TITLE
what's the purpose of "Class" column in the bace.csv file?

### ISSUE THREAD

**Issue by LushengLi9909** [lihan97/KPGT#11]
Thanks for your great work!

I am working on generating latent features for molecules from my datasets using the pre-trained KPGT, so how to define the "Class" like the bace.csv file in my dataset? what's the purpose of this column?

**Comment by lihan97** [comment]
Thank you for your interest in our work!

The "Class" column in the BACE.csv file provides binary labels that indicate whether the molecules can act as inhibitors of human β-secretase 1 (BACE-1).

What is the goal of your task? If you have the binding affinities of molecules targeting a specific protein, you can either use the binding affinities as continuous labels or apply a cutoff to generate binary labels.
