### ISSUE TITLE
RuntimeError: CUDA error: unspecified launch failure

### ISSUE THREAD

**Issue by WangYitian123** [lihan97/KPGT#4]
Hello,

Great job! I encountered an issue when using PyTorch 1.12.0; it displayed the error "ecfp = ecfp.to(self.device) RuntimeError: CUDA error: unspecified launch failure. CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging, consider passing CUDA_LAUNCH_BLOCKING=1." However, when I reverted to PyTorch 1.10.0, it worked. Due to certain reasons, I need to use PyTorch 1.12.0. Can you help me solve this problem?

**Comment by lihan97** [comment]
Apologies for the delayed response.

In my opinion, this error may be related to your python environment or NVIDIA driver. Could you please verify whether other codes run properly with the PyTorch 1.12.0 environment?
